name: "[OBSIDIAN CREATE PLUGIN] Feature request"
description: Suggest an idea for this project
title: "[FR]:"
labels: ["enhancement"]
assignees: 
  - lisandra-dev
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
  - type: checkboxes
    attributes:
      label: Issue validation
      description: "Thanks to check if your issue is relative to the repository. Any non relative or duplicate issue will be closed."
      options:
        - label: "I checked the issue to prevent duplicate"
          required: true
  - type: textarea
    id: describe-request
    attributes:
      label: Is your feature related to a problem ?
      description: If you found a solution with the inherent limit I had with Obsidian, please, add it here! 
      placeholder: "Tell me the original problem"
  - type: textarea
    id: describe-solution
    attributes:
      label: What solution do you want to see ?
      description: Describe your idea here!
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe the alternative you've considered
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Environment
        Please fill out the following information to help us debug the issue.
  - type: dropdown
    id: version
    attributes:
      label: OS
      description: Check your OS if your bug is relative to the Obsidian plugin. Skip otherwise.
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
  - type: dropdown
    id: packageManager
    attributes:
      label: Package manager
      description: What package manager do you use ?
      multiple: false
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: input
    id: packageManager-version
    attributes:
        label: Package manager version
        description: Please copy and paste the version of the package manager you are using.
        placeholder: "1.0.0"
    validations:
        required: true
  - type: input
    id: node-version
    attributes:
        label: Node version
        description: Please copy and paste the version of Node you are using.
        placeholder: "1.0.0"
    validations:
        required: true